# R2DBC configuration
spring.r2dbc.url=r2dbc:postgresql://rc1d-duh000346gjj4bhd.mdb.yandexcloud.net:6432/buratino-postgre-production?targetServerType=master&ssl=true&sslmode=verify-full
spring.r2dbc.username=pashkovske-admin
spring.r2dbc.password=${POSTGRES_PASSWORD}

# Flyway configuration (uses JDBC for migrations)
spring.flyway.url=jdbc:postgresql://rc1d-duh000346gjj4bhd.mdb.yandexcloud.net:6432/buratino-postgre-production?targetServerType=master&ssl=true&sslmode=verify-full
spring.flyway.user=pashkovske-admin
spring.flyway.password=${POSTGRES_PASSWORD}
