spring.application.name=buratino

# Tinkoff API configuration
tinkoff.token=${TINKOFF_API_TOKEN}
account.name=${ACCOUNT_NAME}
invest.connector.token=${TINKOFF_API_TOKEN}

auth.predefined.api-key=${ANONYMOUS_PASSWORD}
